Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,28 +1,65 @@
-name: CI/CD Pipeline
+name: Deploy to ECS
 
 on:
   push:
     branches:
       - main
 
-jobs:
-  build-and-deploy:
-    runs-on: ubuntu-latest
+env:
+  AWS_REGION: eu-central-1
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  ECR_REPOSITORY: ping-pong-production-ecr
+  ECS_CLUSTER: ping-pong-production-cluster
+  ECS_SERVICE: ping-pong-production-ecs-service
 
+jobs:
+  deploy:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Configure Docker Buildx
-        uses: docker/setup-buildx-action@v1
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
+      - name: Set up Docker Buildx cache
+        uses: docker/setup-buildx-action@v2
+
+      - name: Log in to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+      - name: Get ECR password (temporary)
+        id: get-ecr-password
+        run: echo "::set-output name=password::$(aws ecr get-login-password)"
+        
       - name: Build and push Docker image
-        run: |
-          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --push -t ping-pong-production-ecr:latest .
+        uses: docker/build-push-action@v1
+        with:
+          context: .
+          push: true
+          tags: ${{ env.ECR_REPOSITORY }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
+          provenance: false
+          registry: ${{ steps.login-ecr.outputs.registry }}
+          repository: ${{ env.ECR_REPOSITORY}}
+          username: AWS  # temporary
+          password: ${{ steps.get-ecr-password.outputs.password }}  # temporary
 
-      - name: Deploy to ECS
+      - name: Force deployment
         run: |
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 667332577260.dkr.ecr.eu-central-1.amazonaws.com/ping-pong-production-ecr
-          aws ecs update-service --cluster ping-pong-production-cluster --service ping-pong-production-ecs-service --force-new-deployment
+          aws ecs update-service --cluster ${{env.ECS_CLUSTER}} --service ${{env.ECS_SERVICE}} --force-new-deployment
+        id: deploy-ecs
+      
+      - name: Check deployment status
+        run: |
+          if [ "${{ steps.deploy-ecs.outputs.deployment-status }}" != "SUCCESS" ]; then
+            echo "Deployment failed: ${{ steps.deploy-ecs.outputs.deployment-status-reason }}"
+            exit 1
+          fi
